swagger: '2.0'
info:
  title: Petstore
  description: ''
definitions:
  Karol:
    title: Karol
    type: object
    properties:
      id:
        type: string
      greatness_level:
        type: string
